/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package binarytree.Gui;

import binarytree.BinaryTree;
import binarytree.Node;
import javax.swing.JOptionPane;

public class app extends javax.swing.JFrame {
    BinaryTree bt=new BinaryTree();
    String text="aceptar";
    /**
     * Creates new form app
     */
    public app() {
        initComponents();
        disableInput();
        disableButton();
    }

 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        inputApellido = new javax.swing.JEditorPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        inputNumero = new javax.swing.JEditorPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        inputName = new javax.swing.JEditorPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        inputTSangre = new javax.swing.JEditorPane();
        jScrollPane9 = new javax.swing.JScrollPane();
        inputBuscarExpediente = new javax.swing.JEditorPane();
        jButton4 = new javax.swing.JButton();
        botonAceptar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        inputEliminar = new javax.swing.JEditorPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        inputDireccion = new javax.swing.JEditorPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        inputNumeroExpediente = new javax.swing.JEditorPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Agregar nuevo expediente ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("buscar ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Numero Expediente:");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Apellido:");

        jLabel4.setText("Tipo de Sangre:");

        jLabel5.setText("Direccion:");

        jScrollPane4.setViewportView(inputApellido);

        jScrollPane5.setViewportView(inputNumero);

        jScrollPane6.setViewportView(inputName);

        jScrollPane8.setViewportView(inputTSangre);

        jScrollPane9.setViewportView(inputBuscarExpediente);

        jButton4.setText("Modificar expediente ");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        jLabel6.setText("Expediente Clinico");

        jButton5.setText("Eliminar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(inputEliminar);

        jScrollPane2.setViewportView(inputDireccion);

        jScrollPane3.setViewportView(inputNumeroExpediente);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonAceptar)
                .addGap(110, 110, 110))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addComponent(jButton5))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane9)
                                    .addComponent(jScrollPane1)
                                    .addComponent(jScrollPane3))))
                        .addGap(161, 161, 161)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(306, 306, 306)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                    .addComponent(jScrollPane6)
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane8)
                    .addComponent(jScrollPane2))
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel3))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 13, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(botonAceptar))
                .addGap(71, 71, 71))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        enableInput();

        text="Agregar Expediente";
        botonAceptar.setText(text);
        enableButton();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        enableInput();
        text="Actualizar Expediente";
        botonAceptar.setText(text);
        enableButton();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        if(text=="Agregar Expediente")
        {
            agregarNuevoExpediente();
            disableInput();
            cleanEditorPane();
            disableButton();
        }
        else if(text=="Actualizar Expediente")
        {
       
            actualizarExpediente();
            disableInput();
            cleanEditorPane();
            disableButton();
            inputNumeroExpediente.setText("");
        }
    }//GEN-LAST:event_botonAceptarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        buscarExpediente();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        eliminarExpediente();
    }//GEN-LAST:event_jButton5ActionPerformed

    public void agregarNuevoExpediente()
    {
       int i=Integer.parseInt(inputNumero.getText());
       String nombre=inputName.getText();
       String apellido=inputApellido.getText();
       String direccion=inputDireccion.getText();
       String tipoSangre=inputTSangre.getText();
       bt.add(i, nombre, apellido, direccion, tipoSangre);
    }
    public void cleanEditorPane()
    {
        String t="";
        inputNumero.setText(t);
        inputName.setText(t);
        inputApellido.setText(t);
        inputDireccion.setText(t);
        inputTSangre.setText(t);
    }
    public void buscarExpediente()
    {   
        int i=Integer.parseInt(inputBuscarExpediente.getText());
        Node n=new Node();
        n=bt.findNode(i);
        JOptionPane optionPane = new JOptionPane();
        if(n.isEmpty())
        {
            optionPane.showMessageDialog(null, "No Existe el expediente");
        }
        else{
            inputNumero.setText(Integer.toString(i));
            inputName.setText(n.getNombre());
            inputApellido.setText(n.getApellido());
            inputDireccion.setText(n.getDireccion());
            inputTSangre.setText(n.getTipoSangre());          
            inputBuscarExpediente.setText("");
        }
       
    }
    public void actualizarExpediente()
    {
        int i=Integer.parseInt(inputNumeroExpediente.getText());
        String nombre=inputName.getText();
        String apellido=inputApellido.getText();
        String direccion=inputDireccion.getText();
        String tipoSangre=inputTSangre.getText();
        JOptionPane optionPane = new JOptionPane();

        if(bt.update(i, nombre, apellido, direccion, tipoSangre)){
            optionPane.showMessageDialog(null, "Se Actualizo correctamente");
   
        }
        else{
            optionPane.showMessageDialog(null, "no se encontro el numero de expediente");
   
        }
      
    }
    public void eliminarExpediente()
    {
        int i=Integer.parseInt(inputEliminar.getText());
        JOptionPane optionPane = new JOptionPane();
        if(bt.deleteNode(i))
        {
            optionPane.showMessageDialog(null, "Se Elimino el expediente");
            inputEliminar.setText("");
        }
        else{
            optionPane.showMessageDialog(null, "No Existe  el expediente");           
            inputEliminar.setText("");
        }
            
    }
    public void disableInput()
    {
        inputNumero.setEnabled(false);
        inputName.setEnabled(false);
        inputApellido.setEnabled(false);
        inputDireccion.setEnabled(false);
        inputTSangre.setEnabled(false);
    }
    
    public void enableInput()
    {
        inputNumero.setEnabled(true);
        inputName.setEnabled(true);
        inputApellido.setEnabled(true);
        inputDireccion.setEnabled(true);
        inputTSangre.setEnabled(true);
    }
    public void disableButton()
    {
        botonAceptar.setVisible(false);
    }
    public void enableButton()
    {
        botonAceptar.setVisible(true);
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(app.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(app.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(app.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(app.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new app().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JEditorPane inputApellido;
    private javax.swing.JEditorPane inputBuscarExpediente;
    private javax.swing.JEditorPane inputDireccion;
    private javax.swing.JEditorPane inputEliminar;
    private javax.swing.JEditorPane inputName;
    private javax.swing.JEditorPane inputNumero;
    private javax.swing.JEditorPane inputNumeroExpediente;
    private javax.swing.JEditorPane inputTSangre;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    // End of variables declaration//GEN-END:variables

    private void assertFalse(boolean containsNode) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
